-- ============================================================
--  Sessões do Congresso 2026 -> tabela presenca.palestras
--  id = palestra_id usado em participantes (ex.: MOCHILA_M, EJA_N).
--  Fonte dos locais/horários: documento oficial LOCAIS E PALESTRANTES.
--  Rode no SQL Editor do Supabase (projeto do gom).
-- ============================================================

alter table presenca.palestras add column if not exists local     text;
alter table presenca.palestras add column if not exists endereco  text;
alter table presenca.palestras add column if not exists periodo   text;
alter table presenca.palestras add column if not exists hora      text;

-- Upsert das 23 sessões (cria ou atualiza; preserva presencas/participantes).
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('ALEM_TELAS_M', 'Além das Telas: BNCC Computação na Educação Infantil e nos Anos Iniciais.', 'UNAERP - Teatro Bassano Vaccarini', 'Av. Costábile Romano, 2201 - Nova Ribeirânia', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('ALEM_TELAS_T', 'Além das Telas: BNCC Computação na Educação Infantil e nos Anos Iniciais.', 'UNAERP - Teatro Bassano Vaccarini', 'Av. Costábile Romano, 2201 - Nova Ribeirânia', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('ALFABETIZACAO_M', 'Alfabetização em discurso: sentidos para ler e escrever com a literatura infantil.', 'Estácio - Teatro', 'R. Abrahão Issa Halack, 980 - Ribeirânia', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('ALFABETIZACAO_T', 'Alfabetização em discurso: sentidos para ler e escrever com a literatura infantil.', 'Estácio - Teatro', 'R. Abrahão Issa Halack, 980 - Ribeirânia', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('CRIANDO_PONTES_M', 'Criando Pontes no Educar para COMviver: contribuição com atividades funcionais para uma Escola Funcional.', 'UNIP', 'Av. Carlos Consoni, 10 - Jardim Canadá', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('CRIANDO_PONTES_T', 'Criando Pontes no Educar para COMviver: contribuição com atividades funcionais para uma Escola Funcional.', 'UNIP', 'Av. Carlos Consoni, 10 - Jardim Canadá', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('DA_MEMORIA_M', 'Da memória ao futuro: pertencimento e identidade na formação da cidadania.', 'Auditório Meira Junior', 'R. Álvares Cabral, 370 - Centro', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('DA_MEMORIA_T', 'Da memória ao futuro: pertencimento e identidade na formação da cidadania.', 'Auditório Meira Junior', 'R. Álvares Cabral, 370 - Centro', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('EDUCAR_CONVIVER_M', 'Educar para conviver: saúde mental, tecnologias e os desafios da prática docente contemporânea.', 'USP - Auditório (Faculdade de Direito)', 'Av. Bandeirantes, 3900', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('EDUCAR_CONVIVER_T', 'Educar para conviver: saúde mental, tecnologias e os desafios da prática docente contemporânea.', 'USP - Auditório (Faculdade de Direito)', 'Av. Bandeirantes, 3900', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('EDUC_ALIMENTAR_M', 'Educação Alimentar e Nutricional e Seletividade Alimentar nas Escolas.', 'Estácio - Anfiteatro', 'R. Abrahão Issa Halack, 980 - Ribeirânia', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('EDUC_ALIMENTAR_T', 'Educação Alimentar e Nutricional e Seletividade Alimentar nas Escolas.', 'Estácio - Anfiteatro', 'R. Abrahão Issa Halack, 980 - Ribeirânia', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('EJA_N', 'Muito além do conteúdo: o professor da EJA diante das histórias de vida.', 'UNAERP - Sala 06H', 'Av. Costábile Romano, 2201 - Nova Ribeirânia', 'Noite', '19:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('GESTAO_DEMOCRATICA_M', 'Gestão democrática e qualidade na Educação Infantil.', 'SENAI', 'Rua Capitão Salomão, 1813 - Campos Elíseos', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('GESTAO_DEMOCRATICA_T', 'Gestão democrática e qualidade na Educação Infantil.', 'SENAI', 'Rua Capitão Salomão, 1813 - Campos Elíseos', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('INFANCIA_ATIVIDADE_M', 'Infância, atividade física e tecnologia: desafios do terceiro milênio.', 'Centro Universitário Moura Lacerda', 'Rua Padre Euclides, 995 - Campos Elíseos', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('INFANCIA_ATIVIDADE_T', 'Infância, atividade física e tecnologia: desafios do terceiro milênio.', 'Centro Universitário Moura Lacerda', 'Rua Padre Euclides, 995 - Campos Elíseos', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('MOCHILA_M', 'A Mochila do Educador: Nossas memórias como ponte para o pertencimento.', 'Teatro Municipal - Auditório', 'Praça Alto do São Bento, s/n - Campos Elíseos', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('MOCHILA_T', 'A Mochila do Educador: Nossas memórias como ponte para o pertencimento.', 'Teatro Municipal - Auditório', 'Praça Alto do São Bento, s/n - Campos Elíseos', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('PRETO_CAFE_M', 'Ribeirão Preto: o preto do seu povo, o preto do café – cultura, identidade e educação, forças motrizes da região.', 'Centro Universitário Barão de Mauá', 'R. Ramos de Azevedo, 423 - Jardim Paulista', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('PRETO_CAFE_T', 'Ribeirão Preto: o preto do seu povo, o preto do café – cultura, identidade e educação, forças motrizes da região.', 'Centro Universitário Barão de Mauá', 'R. Ramos de Azevedo, 423 - Jardim Paulista', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('QUEM_BRINCA_M', 'Quem brinca escolhe, quem ensina planeja: a intencionalidade no cotidiano da infância.', 'SESI', 'R. João Ignacchitti, 20 - Jardim Castelo Branco', 'Manhã', '08:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values ('QUEM_BRINCA_T', 'Quem brinca escolhe, quem ensina planeja: a intencionalidade no cotidiano da infância.', 'SESI', 'R. João Ignacchitti, 20 - Jardim Castelo Branco', 'Tarde', '14:00') on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;
