-- ============================================================
--  ATUALIZAÇÃO DAS INSCRIÇÕES — export oficial (13/07/2026)
--  Fonte: Relação de Professores com Inscrição Palestras.xlsx
--
--  1) Nova palestra "Diálogos entre o Direito e a Educação" (M/T)
--  3) Cristopher — alinha ao lançamento oficial
--  4) Renomeações de token (quem ganhou a 2ª sessão)
--  5) 32 remoções (saíram do sistema oficial)
--  6) 258 novas inscrições
--
--  0) Garante os ajustes manuais anteriores (idempotente: se você já
--     rodou algum deles, não muda nada; se não rodou, aplica agora)
--  7) Mara (41747): mantém as DUAS palestras (formulário de 06/07)
--  8) Luciano Santos Toniolo (45168): inscrição de última hora
--  9) Avulsos: André (49633) + convidadas externas Elisa e Tássia
--  Rode TUDO de uma vez no SQL Editor do Supabase.
-- ============================================================

begin;

-- 0) GARANTE AJUSTES MANUAIS ANTERIORES (idempotente) --------------
-- Gabriela Stoco: rescindiu 49722, assumiu 50402 (Além das Telas M)
delete from presenca.presencas     where token = '49722';
delete from presenca.participantes where token = '49722';
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('50402','GABRIELA STOCO CORREA DE OLIVEIRA','gabrielafrancisco@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','50402','OFICIAL','ANTONIO PALOCCI, EMEF')
on conflict (token) do update set nome=excluded.nome, email=excluded.email, palestra_id=excluded.palestra_id, codigo_funcional=excluded.codigo_funcional, unidade=excluded.unidade;

-- Gabriela Pizani: rescindiu 48824, assumiu 50460 (Mochila T)
delete from presenca.presencas     where token = '48824';
delete from presenca.participantes where token = '48824';
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('50460','GABRIELA PIZANI SOARES','gabrielasoares@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_T','50460','OFICIAL','CARMEM MASSAROTTO, PROFª., EMEI')
on conflict (token) do update set nome=excluded.nome, email=excluded.email, palestra_id=excluded.palestra_id, codigo_funcional=excluded.codigo_funcional, unidade=excluded.unidade;

-- Inclusões avulsas anteriores (André e Angela)
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('43350','ANDRE ALBUQUERQUE FERREIRA','andreferreira@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','43350','OFICIAL','CELSO CHARURI DR.'),
('49483','ANGELA MARIA DIAS DA SILVA','marciasoares@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_T','49483','OFICIAL','EGYDIO PEDRESCHI, CEEEF')
on conflict (token) do nothing;

-- Gestão Democrática: os dois períodos no SENAI (garante)
update presenca.palestras
set local = 'SENAI', endereco = 'Rua Capitão Salomão, 1813 - Campos Elíseos'
where id in ('GESTAO_DEMOCRATICA_M','GESTAO_DEMOCRATICA_T');

-- 1) NOVA PALESTRA ------------------------------------------------
insert into presenca.palestras (id, nome, local, endereco, periodo, hora) values
('DIALOGOS_DIREITO_M', 'Diálogos entre o Direito e a Educação: contribuições jurídicas para uma gestão escolar inclusiva.', 'USP - Anfiteatro (FEA)', 'Av. Bandeirantes, 3900 - Vila Monte Alegre', 'Manhã', '08:00'),
('DIALOGOS_DIREITO_T', 'Diálogos entre o Direito e a Educação: contribuições jurídicas para uma gestão escolar inclusiva.', 'USP - Anfiteatro (FEA)', 'Av. Bandeirantes, 3900 - Vila Monte Alegre', 'Tarde', '14:00')
on conflict (id) do update set nome=excluded.nome, local=excluded.local, endereco=excluded.endereco, periodo=excluded.periodo, hora=excluded.hora;

alter table presenca.palestras add column if not exists capacidade integer;
update presenca.palestras set capacidade = 95 where id in ('DIALOGOS_DIREITO_M','DIALOGOS_DIREITO_T');

-- 3) CRISTOPHER — alinha ao lançamento oficial --------------------
update presenca.participantes set palestra_id='QUEM_BRINCA_T' where token='40030';
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('38268','CRISTOPHER RIBEIRO MERCALDI','cristophermercaldi@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_M','38268','OFICIAL','JOSE BONIFACIO COUTINHO NOGUEIRA, EMEI')
on conflict (token) do update set palestra_id=excluded.palestra_id;

-- 4) RENOMEAÇÕES DE TOKEN ----------------------------------------
update presenca.participantes set token='39626_M' where token='39626' and palestra_id='ALFABETIZACAO_M';
update presenca.participantes set token='33832_M' where token='33832' and palestra_id='EDUCAR_CONVIVER_M';
update presenca.participantes set token='50262_T' where token='50262' and palestra_id='ALFABETIZACAO_T';
update presenca.participantes set token='47821_T' where token='47821' and palestra_id='GESTAO_DEMOCRATICA_T';
update presenca.participantes set token='47740_M' where token='47740' and palestra_id='GESTAO_DEMOCRATICA_M';
update presenca.participantes set token='40169_M' where token='40169' and palestra_id='PRETO_CAFE_M';
update presenca.participantes set token='43889_T' where token='43889' and palestra_id='INFANCIA_ATIVIDADE_T';
update presenca.participantes set token='47026_M' where token='47026' and palestra_id='EDUCAR_CONVIVER_M';
update presenca.participantes set token='49102_T' where token='49102' and palestra_id='INFANCIA_ATIVIDADE_T';
update presenca.participantes set token='43355_M' where token='43355' and palestra_id='DA_MEMORIA_M';
update presenca.participantes set token='31513_M' where token='31513' and palestra_id='ALEM_TELAS_M';

-- 5) REMOÇÕES (32) — saíram do sistema oficial ----------
delete from presenca.presencas     where token in ('38232','44177','46290','49835','50158','36696_T','46325','48889','47783','38437','47832','38246','34556_M','42419_M','38145','36696_M','47814','31088','49197','40104','38344','39980','48037','47850','38428','47743','48028_T','48028_M','50310','50342','41201','49452');
delete from presenca.participantes where token in ('38232','44177','46290','49835','50158','36696_T','46325','48889','47783','38437','47832','38246','34556_M','42419_M','38145','36696_M','47814','31088','49197','40104','38344','39980','48037','47850','38428','47743','48028_T','48028_M','50310','50342','41201','49452');

-- 6) NOVAS INSCRIÇÕES (258) ---------------------------------
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('35189','ADHEMAR MARQUES BONADIO',NULL,NULL,'ALEM_TELAS_M','35189','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('32447','ANA GABRIELA GRAMANI SAY','anasay@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','32447','OFICIAL','ALOIZIO OLAIA PASCHOAL, EMEI'),
('49535','ELAINE CAPRETZ BORGES DA SILVA DORNE',NULL,NULL,'ALEM_TELAS_M','49535','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('39317','FLAVIA MAJOY DA SILVA','flaviamajoy@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','39317','OFICIAL','WILSON ROSELINO, EMEI'),
('38145','GIOVANA VILA MARCOVIG VASCO MEDEIROS','giovanamedeiros@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','38145','OFICIAL','THOMAZ URBINATTI, CEI'),
('49257','JULIANA DONATTI',NULL,NULL,'ALEM_TELAS_M','49257','OFICIAL','ANTONIO PALOCCI, EMEF'),
('34452','REGIANE CRISTINA AGOSTINO','regianeagostino@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','34452','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('35220','WILLIAM BALIEIRO',NULL,NULL,'ALEM_TELAS_M','35220','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50445','AMANDA BEATRIZ ALVES TUROLE',NULL,NULL,'ALEM_TELAS_T','50445','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49400','CLAUDIA LUIZA LAPRIA POLO','claudiapolo@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_T','49400','OFICIAL','CARMEM MASSAROTTO, PROFª., EMEI'),
('39626_T','MARISLEI APARECIDA CATANI DE OLIVEIRA','marisleioliveira@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_T','39626','OFICIAL','RAUL MACHADO, PROFº., EMEF'),
('50311','RENATA SCRIDELI SANTOS',NULL,NULL,'ALEM_TELAS_T','50311','OFICIAL','MARIA INES VIEIRA MACHADO, PROFª., EMEF'),
('50158','SUSANA PENTEADO DELLA COLLETA','susanacolleta@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_T','50158','OFICIAL','MARIA INES VIEIRA MACHADO, PROFª., EMEF'),
('48227','ANA CAROLINA ROCCO DIAS RESTINI','anacarolinarestini@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_M','48227','OFICIAL','JOSE DELIBO, VER., EMEF'),
('49562','INGRID SPINELLI MALAGUTI PACHECO',NULL,NULL,'ALFABETIZACAO_M','49562','OFICIAL','ANISIO TEIXEIRA, PROFº., EMEF'),
('49452','JESSICA DE SOUZA BRAZ BECARI','jessicabecari@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_M','49452','OFICIAL','JOSE CARLOS SOBRAL, DR., EMEI'),
('49835','MARIANA BALIEIRO PEREIRA','marianapereira@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_M','49835','OFICIAL','JOSE DELIBO, VER., EMEF'),
('42447_M','ROGERIO APARECIDO NOVAES BARBOSA','rogeriobarbosa@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_M','42447','OFICIAL','JOSE DELIBO, VER., EMEF'),
('36696_T','GRAZIELE FRANCINE MATTA DE ALVARENGA','grazielealvarenga@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_T','36696','OFICIAL','IRIA JUNQUEIRA, DONA, EMEI'),
('50061','JULIANA FREITAS MOREIRA ALVES',NULL,NULL,'ALFABETIZACAO_T','50061','OFICIAL','ALCINA DOS SANTOS HECK, EMEF'),
('50324','MARIA BEATRIZ RIBEIRO PRANDI GONCALVES',NULL,NULL,'ALFABETIZACAO_T','50324','OFICIAL','OPUS DEI, CEI'),
('49054','MARINA VENTURI RASSI','marinarassi@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_T','49054','OFICIAL','CARMEM MASSAROTTO, PROFª., EMEI'),
('48889','NATASHA OHANA GINATTO DE FREITAS','natashafreitas@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_T','48889','OFICIAL','ZILDA COSSA D AVILA, EMEI'),
('33832_T','SHIRLEY TELES BARBOSA RUFINO','shirleyrufino@educacao.pmrp.sp.gov.br',NULL,'ALFABETIZACAO_T','33832','OFICIAL','HILDA MARIA SOBRAL BARBOSA MANDARINO, EMEI'),
('50323','VIVIANE ORIENTE DE OLIVEIRA VIEIRA',NULL,NULL,'ALFABETIZACAO_T','50323','OFICIAL','OPUS DEI, CEI'),
('48437','ANA LUISA LANDI',NULL,NULL,'CRIANDO_PONTES_M','48437','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('38437','CAMILA BALIEIRO SIMOES MARTINS','camilamartins@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','38437','OFICIAL','THOMAZ URBINATTI, CEI'),
('38246','CARLA APARECIDA DE MAXIMO PERIM','carlaperim@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','38246','OFICIAL','THOMAZ URBINATTI, CEI'),
('49287','DAIANE ROBERTA DE SOUSA','daianeroberta@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','49287','OFICIAL','WILSON ROSELINO, EMEI'),
('31095','GISELE CRISTINA MARIANO','giselemariano@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','31095','OFICIAL','NAIR MANOELINA DE OLIVEIRA, CEI'),
('36696_M','GRAZIELE FRANCINE MATTA DE ALVARENGA','grazielealvarenga@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','36696','OFICIAL','IRIA JUNQUEIRA, DONA, EMEI'),
('31088','MARISTELA CUBA','maristelacuba@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','31088','OFICIAL','THOMAZ URBINATTI, CEI'),
('49197','NATASHA OHANA GINATTO DE FREITAS','natashafreitas@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','49197','OFICIAL','IRIA JUNQUEIRA, DONA, EMEI'),
('40104','PATRICIA BORGES GIMENES','patriciagimenes@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','40104','OFICIAL','JOSE PEDRO MOREIRA, PROFº., EMEI'),
('38344','SANDRA BOSCHINI BERMUDES','sandrabermudes@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','38344','OFICIAL','THOMAZ URBINATTI, CEI'),
('38123','SANDRA ELISA CRISTOFARO VIRGINIO DOS SANTOS','sesantos@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','38123','OFICIAL','THOMAZ URBINATTI, CEI'),
('39980','SEYLEN CRISTINA GOMES THOMAZELLI','seylengomes@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','39980','OFICIAL','THOMAZ URBINATTI, CEI'),
('48037','SHEILA BORGES GIMENES DE CAMPOS','sheilacampos@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','48037','OFICIAL','QUINTINO VIEIRA, CEI'),
('50262_M','SIMONE COSTA TEIXEIRA','simoneteixeira@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_M','50262','OFICIAL','JOSE RODINI LUIZ PROFº., EMEF'),
('50423','ANDREA DO NASCIMENTO LEITE',NULL,NULL,'CRIANDO_PONTES_T','50423','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49986','DAIANE ZANINELI GOMES AMARAL','daianeamaral@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_T','49986','OFICIAL','ALOIZIO OLAIA PASCHOAL, EMEI'),
('50172','GABRIEL CHAVES ALICINIO','gabrielalicinio@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_T','50172','OFICIAL','JOSE PEDRO MOREIRA, PROFº., EMEI'),
('48741','JUAN FELIPE FERNANDES GOMEZ RODRIGUEZ','jrodriguez@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_T','48741','OFICIAL','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF'),
('49591','KARINA PEREIRA NUNES LUIZ FILHO',NULL,NULL,'CRIANDO_PONTES_T','49591','OFICIAL','SEBASTIAO DE AGUIAR AZEVEDO, EMEF - UN. II'),
('38428','KARLA MOTA DA FONSECA MACHADO','karlamachado@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_T','38428','OFICIAL','THOMAZ URBINATTI, CEI'),
('50284','PAULA LETICIA FONSECA','paulafonseca@educacao.pmrp.sp.gov.br',NULL,'CRIANDO_PONTES_T','50284','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50313','TAUANA GRANDINE CARRASCOSA DE OLIVEIRA',NULL,NULL,'CRIANDO_PONTES_T','50313','OFICIAL','DOMINGOS ANGERAMI, PROFº., EMEF'),
('50435','ALINE CRISTINA ALVES DE MATTOS',NULL,NULL,'DA_MEMORIA_M','50435','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49413','ANA CAROLINA DAVID FERRACINI',NULL,NULL,'DA_MEMORIA_M','49413','OFICIAL','NELSON MACHADO, EMEF'),
('48745','IGOR LUJAN FURQUIM QUEIROZ','igorqueiroz@educacao.pmrp.sp.gov.br',NULL,'DA_MEMORIA_M','48745','OFICIAL','ALFEU LUIZ GASPARINI, PROFº., EMEF'),
('50312','ELIETE OLIVEIRA RODRIGUES',NULL,NULL,'DA_MEMORIA_T','50312','OFICIAL','DOMINGOS ANGERAMI, PROFº., EMEF'),
('49150','JOAO PEDRO DUARTE CARVALHO',NULL,NULL,'DA_MEMORIA_T','49150','OFICIAL','ANTONIO PALOCCI, EMEF'),
('48425_T','VERONICA SAMARA DOS SANTOS VIEIRA',NULL,NULL,'DA_MEMORIA_T','48425','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('49340','ADRIANA CUNHA PEREIRA DA SILVA',NULL,NULL,'DIALOGOS_DIREITO_M','49340','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47820','ALINE BRUNA BARBOSA ARAUJO FROES','alinefroes@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47820','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47908','ALINE PRATALI RIBEIRO','alinepratali@educacao.pmrp.sp.gov.b',NULL,'DIALOGOS_DIREITO_M','47908','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47770','AMANDA CORDEIRO DOS SANTOS','amandacordeiro@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47770','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48467','ANA PAULA DIAS',NULL,NULL,'DIALOGOS_DIREITO_M','48467','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47756','ANDRE LUIS FERREIRA MARTINS','andremartins@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47756','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47731','ANGELA KATIA CIRIACO BISPO MELO','angelabispo@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47731','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47789','BELGUER WILCLES MACARINI','belguermacarini@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47789','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47832','CARLA ALYRIA MARQUES','carlaassis@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47832','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48546','CAROLINA MAULIM E SILVA SANTIAGO',NULL,NULL,'DIALOGOS_DIREITO_M','48546','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47746','CAROLINE BARRETO BRUNELLI BARBOSA','regianeavanci@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47746','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47821_M','CINTIA CLAUDINO SILVERIO','cintiasilverio@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47821','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47783','DANIELE CANDIDA DA SILVA REIS','danielereis@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47783','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47845','DANUBIA CAROLINE DOS SANTOS','danubiasantos@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47845','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47767','DEJANE DE ALMEIDA PAULINO','dejanepaulino@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47767','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47734','DIANE RODRIGUES NILSON','dianenilson@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47734','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47776','ERICA DINAH DE OLIVEIRA DOS SANTOS','ericasantos@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47776','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47748','FLAVIA MARIANA FERNANDES DE MOURA','fmoura@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47748','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48094','GEREMIAS FRANCO CARNIEL RIGOBELLO','geremiasrigobello@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48094','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47849','GIOVANNA CRISTINA DE OLIVEIRA','giovannaoliveira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47849','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48752','GISLAINE ANDREA PEREIRA','gislainepereira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48752','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48434','GRACA DAIANE CARASSATO DE SOUZA',NULL,NULL,'DIALOGOS_DIREITO_M','48434','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47996','GUSTAVO KAIQUE SOARES','gustavosoares@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47996','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47784','JOEL LUIZ PEREIRA','joelpereira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47784','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47791','JOSIANE RODRIGUES OLIVEIRA DE LUCENA','josianelucena@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47791','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48011_M','KATIA MARIA GIANNINI','katiagiannini@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48011','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47812','KELI BENTO BARROS NARDI','kelinardi@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47812','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48189','LARISSA CRISTINE GOUVEA',NULL,NULL,'DIALOGOS_DIREITO_M','48189','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47835','LEANDRO LINO GONÇALVES RODRIGUES','leandrorodrigues@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47835','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47769','LETICIA CORREA MEDEIROS','leticiamedeiros@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47769','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48151','LIA CINTHIA FERREIRA','liaferreira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48151','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47851','MARCIA APARECIDA NOVATO DE SOUSA','marcianovato@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47851','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47800','MARILIA ALIARDE','mariliaaliarde@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47800','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47711','MARISTELA ZEVIANI','maristelazeviani@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47711','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47710','MERCIA DIANA COTA FERREIRA','merciaferreira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47710','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48014','MICHELE ROCHA DE OLIVEIRA MARTINS','michelemartins@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48014','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47766','PATRICIA ALVES RODRIGUES LEITE','patricialeite@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47766','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48556','ROSANE VICTORINO DA ROCHA CINTRA',NULL,NULL,'DIALOGOS_DIREITO_M','48556','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47741_M','ROSANGELA LAGO SILVEIRA','rosangelasilveira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47741','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47743','SABRINA CUSTODIO CORCINO DE SOUZA','sabrinasouza@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47743','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47954','SANDRA PAES LEME NUNES','snunes@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47954','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47891','SILMARA GONCALVES PESTANA','silmarapestana@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47891','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47795','SOLANGE CARACHO PEREIRA','solangepereira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47795','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47847','THAIS HELENA PEREIRA BERNARDES','thaisbernardes@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47847','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47713','THELMA DE LIMA PEIXOTO','thelmapeixoto@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','47713','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48161','VANESSA DE LUCA','vanessadeluca@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48161','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48032','ZILDA VIEIRA DOS SANTOS CAMPANINI','zildacampanini@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_M','48032','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47830','ALEX JULIANO LEMES RODRIGUES ELIAS','alexelias@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47830','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47893','ALEXIA CRISTINA DE SOUSA','alexiasousa@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47893','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47759','AMANDA FERNANDES BRITO','amandabrito@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47759','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47774','ANA PATRICIA RIBEIRO DA SILVA','anapatricia@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47774','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47747','ANA PAULA PAES LEME','analeme@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47747','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47797_T','ANDRE LUIS DE SOUZA GOULART','andregoulart@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47797','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47723','ANNELISE SIMARI CARREIRA LEITE','anneliseleite@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47723','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50291','ANSELMO BELAN','anselmobelan@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','50291','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48022','CARLA ROBERTA DESERTOLI','carladesertoli@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','48022','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50296','CARMELITA DE AMORIM SIMAO',NULL,NULL,'DIALOGOS_DIREITO_T','50296','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47758','CASSIO ROBERTO GONZALES JUNIOR','cjunior@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47758','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47840','CIBELE ZANATTA DA SILVA PEREIRA','cibelepereira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47840','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48029','DAIANA APARECIDA GUIRALDELI DOS ANJOS','daianaguiraldeli@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','48029','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47760','DEJAIME DE OLIVEIRA RIBEIRO','dejaimeribeiro@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47760','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47735','EDIANA GOMES DA SILVA','egsilva@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47735','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47811','ERICK ROBERTO FREIRE DE ARAUJO SILVA','ericksilva@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47811','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47828','FELIPE SOUZA BAZEIO','felipebazeio@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47828','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47761','FLAVIA TAMBURUS CHIARETTI','flaviachiaretti@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47761','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48052','GEISA GABRIELE SILVA MELO GONCALVES','geisagoncalves@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','48052','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47909','GERMANO DE JESUS TOBIAS','germanotobias@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47909','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47779','IDALETE DA SILVA','idaletesilva@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47779','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47787','JACQUELINE PISCHIOTTIN IOSSI','jacquelineiossi@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47787','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48481','JOAO ROGERIO CARNEIRO',NULL,NULL,'DIALOGOS_DIREITO_T','48481','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50438','JOSE MARCIO DA SILVA',NULL,NULL,'DIALOGOS_DIREITO_T','50438','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47740_T','JULIANA FERREIRA LEITE DA SILVA','julianaleite@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47740','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47814','LARISSA APARECIDA TRINDADE','larissatrindade@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47814','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49563','LEANDRO RODRIGUES MORAIS',NULL,NULL,'DIALOGOS_DIREITO_T','49563','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47771','LIDIA LYRA CORDEIRO PORTO','lidiaporto@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47771','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48159','LUCIANA STELA DE OLIVEIRA','lucianaoliveira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','48159','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47880','LUCIMARA ALVES FARIAS','lucimarafarias@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47880','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50452','MAIARA CRISTINA MORAES',NULL,NULL,'DIALOGOS_DIREITO_T','50452','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50237','MARCELO BERNINE',NULL,NULL,'DIALOGOS_DIREITO_T','50237','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47745','MARCIO DA SILVA','mdsilva@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47745','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47742','MAURICIO ORTIZ NETO','mauricioneto@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47742','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47852_T','MIRIAN QUEIROZ DE SOUZA DANIEL','miriandaniel@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47852','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50322','PATRICIA FABIOLA FERREIRA','patriciafferreira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','50322','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('48028','RAPHAELA HENRIQUES RAPOSO','raphaelaraposo@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','48028','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47739','RICARDO ALEXANDRE PEREIRA','ricardopereira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47739','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47744','ROSEMEIRE CEZARIO FRANCISCO','rosemeirefrancisco@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47744','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48562','SAMUEL RODRIGUES PINTO',NULL,NULL,'DIALOGOS_DIREITO_T','48562','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47953','SANDRA DOS REIS COELHO ZANELLA','sandrazanella@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47953','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47718','SELMA REGINA FURIO VIEIRA','selmavieira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47718','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47752','SHIRLEY FABIANA PEREIRA LEMES','shirleylemes@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47752','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47720','SIMEI DARIO VIANA DOS SANTOS','simeisantos@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47720','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47716','SUELI APARECIDA VIEIRA','suelivieira@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47716','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47843','TAINA JACOMINI DE SOUZA','tainasouza@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47843','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47829','TALES HENRIQUE MATOS BASTOS','talesbastos@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47829','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47777','THAIS COUTINHO BARBOSA','thaisbarbosa@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47777','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('47850','VAGNER DUTRA DA SILVA','vagnersilva@educacao.pmrp.sp.gov.br',NULL,'DIALOGOS_DIREITO_T','47850','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50444','VIVIANE ANDRADE BANDEIRA',NULL,NULL,'DIALOGOS_DIREITO_T','50444','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('35207_M','ALESSANDRA MARQUES TONELLI',NULL,NULL,'EDUCAR_CONVIVER_M','35207','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48901','ANA CAROLINA BUENO',NULL,NULL,'EDUCAR_CONVIVER_M','48901','OFICIAL','JOSE RODINI LUIZ PROFº., EMEF'),
('50068','DAIANE BORGES DOS SANTOS','daianeborges@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','50068','OFICIAL','NELSON MACHADO, EMEF'),
('49377','EDUARDO CAMARGO ARCARI',NULL,NULL,'EDUCAR_CONVIVER_M','49377','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('48368','ICARO GIOVANE DE SOUZA OLIVEIRA',NULL,NULL,'EDUCAR_CONVIVER_M','48368','OFICIAL','ANTONIO PALOCCI, EMEF'),
('37787','ISABEL CRISTINA RIBEIRO GARCIA','isabelgarcia@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','37787','OFICIAL','PAULO HENRIQUE DE SOUZA, EMEI'),
('39605','JOSE ORLANDO DE SOUZA FELIPE','josefelipe@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','39605','OFICIAL','ANTONIO PALOCCI, EMEF'),
('49166','KARINA MACHADO GOMES',NULL,NULL,'EDUCAR_CONVIVER_M','49166','OFICIAL','ANTONIO PALOCCI, EMEF'),
('35277','KARLA MATOS DA SILVA',NULL,NULL,'EDUCAR_CONVIVER_M','35277','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48362','LARISSA DA SILVA QUALIO',NULL,NULL,'EDUCAR_CONVIVER_M','48362','OFICIAL','MOACIR FIRMINO, EMEI'),
('45334','LEONARDO DE BRITO LOPES','leonardolopes@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','45334','OFICIAL','ANTONIO PALOCCI, EMEF'),
('49399_M','PATRICK CESAR AMARAL FERREIRA',NULL,NULL,'EDUCAR_CONVIVER_M','49399','OFICIAL','DOMINGOS ADILSON CANESIN, EMEF'),
('38873','PRISCILA GEROLAMO ALVES MILANEZ','priscilamilanez@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','38873','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('39358','REGIANE DE CASSIA LEAO ARAUJO','regianearaujo@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','39358','OFICIAL','QUINTINO VIEIRA, CEI'),
('43455','RODOLFO DE SOUZA RODRIGUES','rodolforodrigues@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_M','43455','OFICIAL','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF'),
('43641_T','CAIO MARCO ESPIMPOLO','caioespimpolo@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_T','43641','OFICIAL','JOSE DELIBO, VER., EMEF'),
('49177_T','CARLA CRISTINA PESSOA KFOURI',NULL,NULL,'EDUCAR_CONVIVER_T','49177','OFICIAL','AUREA APARECIDA BRAGHETTO MACHADO, EMEI'),
('48926_T','FRANCIELE CRISTINA MARQUES DA SILVA SBROLIN',NULL,NULL,'EDUCAR_CONVIVER_T','48926','OFICIAL','CARMEN APARECIDA DE CARVALHO RAMOS, EMEI'),
('49106','GABRIELLE YUMI HIGASHIJIMA CAPRETZ',NULL,NULL,'EDUCAR_CONVIVER_T','49106','OFICIAL','WALDEMAR ROBERTO, PROF.,DR., EMEF'),
('48207','KANANDA KAIRALA MOTA ROSA',NULL,NULL,'EDUCAR_CONVIVER_T','48207','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('48011_T','KATIA MARIA GIANNINI','katiagiannini@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_T','48011','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49459','LETICIA REGINA DE OLIVEIRA',NULL,NULL,'EDUCAR_CONVIVER_T','49459','OFICIAL','SEBASTIAO DE AGUIAR AZEVEDO, EMEF - UN. II'),
('50342','MARCIA ANGELICA VIEIRA','marciasouza@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_T','50342','OFICIAL','RAUL MACHADO, PROFº., EMEF'),
('50314','MARIANA BRITO GOMES DA SILVA',NULL,NULL,'EDUCAR_CONVIVER_T','50314','OFICIAL','PAULO FREIRE, PROFº., EMEF'),
('50459','MELISE GABRIELA DOS SANTOS',NULL,NULL,'EDUCAR_CONVIVER_T','50459','OFICIAL','HILDA MOSCA, EMEI'),
('49517','OLGA MARA RISSI NEVES','olganeves@educacao.pmrp.sp.gov.br',NULL,'EDUCAR_CONVIVER_T','49517','OFICIAL','TERESA HENDRICA ANTONISSEN, EMEI'),
('49494','PAULO CESAR DA SILVA ANDREUCCI',NULL,NULL,'EDUCAR_CONVIVER_T','49494','OFICIAL','VIRGILIO SALATA, EMEF'),
('49506','RAFAEL ROBERTO DA SILVA',NULL,NULL,'EDUCAR_CONVIVER_T','49506','OFICIAL','GERALDA DE SOUZA ESPIN, EMEF'),
('49662_M','ALAN DE MARCO BARBOSA',NULL,NULL,'EDUC_ALIMENTAR_M','49662','OFICIAL','PAULO FREIRE, PROFº., EMEF'),
('38129','ANA CLARISSA DA SILVA MEDEIROS','anamedeiros@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_M','38129','OFICIAL','MOACIR FIRMINO, EMEI'),
('48398','CAMILA ROCHA OLIVEIRA',NULL,NULL,'EDUC_ALIMENTAR_M','48398','OFICIAL','PAULO MONTE SERRAT FILHO, PROFº., DR., EMEF'),
('40075','CRISTIANO RICARDO BARBOSA DEL LAMA','cristianolama@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_M','40075','OFICIAL','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF'),
('49171','DENISE FONSECA SANTOS APOLINARIO',NULL,NULL,'EDUC_ALIMENTAR_M','49171','OFICIAL','LILIAN SPADARO ROSA E SILVA, PROFª., EMEI'),
('39933','FERNANDA SALVINO FREGONEZI','fernandasalvino@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_M','39933','OFICIAL','JOAO DA CRUZ MOREIRA, CEI'),
('49306','LAURA MARCHESIN GODELI',NULL,NULL,'EDUC_ALIMENTAR_M','49306','OFICIAL','TEREZINHA, SANTA, EMEI'),
('38328','LUCIANO GONCALVES TEODORO','lucianoteodoro@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_M','38328','OFICIAL','ROSA MARIA DE BRITTO COSENZA, CEI'),
('49005','CARINE ZILLMER FERRAZ',NULL,NULL,'EDUC_ALIMENTAR_T','49005','OFICIAL','JOAO GILBERTO SAMPAIO, DR., EMEF'),
('43823','MARIANA BORGES TEIXEIRA ITO','mbtito@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_T','43823','OFICIAL','MIGUEL MUSSI, EMEI'),
('50310','VALERIA ANDRADE SILVA DREOSSI','valeriadreossi@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_T','50310','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('40169_N','PATRICIA DE MORAIS NOGUEIRA','patricianogueira@educacao.pmrp.sp.gov.br',NULL,'EJA_N','40169','OFICIAL','ALFEU LUIZ GASPARINI, PROFº., EMEF'),
('43575','REINALDO PEREIRA DA SILVA JUNIOR','reinaldojunior@educacao.pmrp.sp.gov.br',NULL,'EJA_N','43575','OFICIAL','JOSE RODINI LUIZ PROFº., EMEF'),
('47797_M','ANDRE LUIS DE SOUZA GOULART','andregoulart@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_M','47797','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('43641_M','CAIO MARCO ESPIMPOLO','caioespimpolo@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_M','43641','OFICIAL','JOSE DELIBO, VER., EMEF'),
('47852_M','MIRIAN QUEIROZ DE SOUZA DANIEL','miriandaniel@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_M','47852','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49571','TATIANE SOARES DE AZEVEDO DUARTE',NULL,NULL,'GESTAO_DEMOCRATICA_M','49571','OFICIAL','MARLENE JORGE DOS REIS, EMEI'),
('47905','ANDRESSA MARQUES FORTE SILVA','andressasilva@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_T','47905','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49698','AURIA DE CASTRO MOURA','auriamoura@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_T','49698','OFICIAL','FAUSTINO JARRUCHE, EMEF'),
('47741_T','ROSANGELA LAGO SILVEIRA','rosangelasilveira@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_T','47741','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('48879','YASMIN RIBEIRO LOURENCO','yasminlourenco@educacao.pmrp.sp.gov.br',NULL,'GESTAO_DEMOCRATICA_T','48879','OFICIAL','DEOLINDA GASPARINI, CEI'),
('49177_M','CARLA CRISTINA PESSOA KFOURI',NULL,NULL,'INFANCIA_ATIVIDADE_M','49177','OFICIAL','AUREA APARECIDA BRAGHETTO MACHADO, EMEI'),
('50350','LEILA APARECIDA ALVES',NULL,NULL,'INFANCIA_ATIVIDADE_M','50350','OFICIAL','JOAO DA CRUZ MOREIRA, CEI'),
('38935','MARIANA MOURA BARBOZA LAVESSO','marianalavesso@educacao.pmrp.sp.gov.br',NULL,'INFANCIA_ATIVIDADE_M','38935','OFICIAL','CLORESDITH FERLIN FERREIRA, CEI'),
('49165','MIRO AKIRA GUIMARAES YOGI',NULL,NULL,'INFANCIA_ATIVIDADE_M','49165','OFICIAL','AUREA APARECIDA BRAGHETTO MACHADO, EMEI'),
('48350','ROSANA APARECIDA DE SOUZA',NULL,NULL,'INFANCIA_ATIVIDADE_M','48350','OFICIAL','NEUZA MICHELUTTI MARZOLA, PROFª., EMEF'),
('39043','ADA CRISTIANI FERREIRA','adaferreira@educacao.pmrp.sp.gov.br',NULL,'INFANCIA_ATIVIDADE_T','39043','OFICIAL','MARIA DE LOURDES GULLACI LAGUNA PROFA, CEI'),
('49662_T','ALAN DE MARCO BARBOSA',NULL,NULL,'INFANCIA_ATIVIDADE_T','49662','OFICIAL','PAULO FREIRE, PROFº., EMEF'),
('48902','LILIA MICHELE DE ALMEIDA ALVES',NULL,NULL,'INFANCIA_ATIVIDADE_T','48902','OFICIAL','SEBASTIAO DE AGUIAR AZEVEDO, EMEF - UN. II'),
('30792','ROSILENE MARIA DUTRA DE ANDRADE','rosileneandrade@educacao.pmrp.sp.gov.br',NULL,'INFANCIA_ATIVIDADE_T','30792','OFICIAL','AUREA APARECIDA BRAGHETTO MACHADO, EMEI'),
('49569','CAMILA FERREIRA BARBOSA',NULL,NULL,'MOCHILA_M','49569','OFICIAL','ANTONIO PALOCCI, EMEF'),
('49528','CLAUDIO ARRUDA MARTINS BRITO','claudiobrito@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','49528','OFICIAL','NEUZA MICHELUTTI MARZOLA, PROFª., EMEF'),
('45199','CLAUDIO DELFINI','claudiodelfini@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','45199','OFICIAL','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF'),
('42419_M','DIEGO ESCUDERO MARTINS','diegomartins@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','42419','OFICIAL','JOSE PEDRO MOREIRA, PROFº., EMEI'),
('48926_M','FRANCIELE CRISTINA MARQUES DA SILVA SBROLIN',NULL,NULL,'MOCHILA_M','48926','OFICIAL','CARMEN APARECIDA DE CARVALHO RAMOS, EMEI'),
('38439','JANAINA FARIA DE SOUZA','janainasouza@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','38439','OFICIAL','ANITA PROCOPIO JUNQUEIRA, EMEI'),
('38443','JOSIANA BOTELHO BIDIO','josianabidio@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','38443','OFICIAL','QUINTINO VIEIRA, CEI'),
('36661','RITA HELENA PORFIRIO','ritaaraujo@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','36661','OFICIAL','MIGUEL MUSSI, EMEI'),
('43889_M','SUSAN ROBERTA DE OLIVEIRA LIMA','susan@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_M','43889','OFICIAL','HENILLA GODOY VELLUDO SALVADOR, EMEI'),
('48425_M','VERONICA SAMARA DOS SANTOS VIEIRA',NULL,NULL,'MOCHILA_M','48425','OFICIAL','JAIME MONTEIRO DE BARROS DR., EMEF'),
('50425','ALINE MARQUES MIRANDA',NULL,NULL,'MOCHILA_T','50425','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('44177','BIANCA LETICIA CASTALDELLI','biancacastaldelli@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_T','44177','OFICIAL','JOSE DELIBO, VER., EMEF'),
('49856','FLAVIA MAYUMI KANASHIRO','flaviakanashiro@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_T','49856','OFICIAL','DOMINGOS ADILSON CANESIN, EMEF'),
('47026_T','GISELLE JULIANA CLEMENCIO FERREIRA','giselleferreira@educacao.pmrp.sp.gov.br',NULL,'MOCHILA_T','47026','OFICIAL','MARLENE JORGE DOS REIS, EMEI'),
('50308','ISABEL CRISTINA PAIM ROSSI',NULL,NULL,'MOCHILA_T','50308','OFICIAL','LUCIO MENDES, CEI'),
('49611','ROMER FERREIRA',NULL,NULL,'MOCHILA_T','49611','OFICIAL','PAULO FREIRE, PROFº., EMEF'),
('35214_T','YNAE PRADO MATTENHAUER',NULL,NULL,'MOCHILA_T','35214','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('29204','ARNALDO MARTINEZ DE BACCO JUNIOR','arnaldojunior@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_M','29204','OFICIAL','LUIS DO AMARAL MOUSINHO, DOM, EMEF'),
('49607','CAMILA PIRES CARDOSO',NULL,NULL,'PRETO_CAFE_M','49607','OFICIAL','JOSE DELIBO, VER., EMEF'),
('49211','EDMEA ROSANGELA KOVALESKI',NULL,NULL,'PRETO_CAFE_M','49211','OFICIAL','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF'),
('49102_M','EMANUEL VALENTIM DOS SANTOS','emanuelsantos@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_M','49102','OFICIAL','NEUZA MICHELUTTI MARZOLA, PROFª., EMEF'),
('48361','IASMIM TIZZIOTTI PETACCI',NULL,NULL,'PRETO_CAFE_M','48361','OFICIAL','LUIS DO AMARAL MOUSINHO, DOM, EMEF'),
('49243','JACKELINE OLIVEIRA DE SOUZA E SILVA',NULL,NULL,'PRETO_CAFE_M','49243','OFICIAL','SEBASTIAO DE AGUIAR AZEVEDO, EMEF - UN. II'),
('48432','JULIANA FREITAS MOREIRA ALVES',NULL,NULL,'PRETO_CAFE_M','48432','OFICIAL','ALCINA DOS SANTOS HECK, EMEF'),
('48911','ROSANA MOURAO','rosanamourao@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_M','48911','OFICIAL','ALOIZIO OLAIA PASCHOAL, EMEI'),
('35214_M','YNAE PRADO MATTENHAUER',NULL,NULL,'PRETO_CAFE_M','35214','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50321','DANIEL RODRIGO DOS SANTOS RIGO',NULL,NULL,'PRETO_CAFE_T','50321','OFICIAL','DOMINGOS ADILSON CANESIN, EMEF'),
('41201','FLAVIA APARECIDA PELLEGI GONCALVES','flaviagoncalves@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','41201','OFICIAL','HORTENCIO PEREIRA DA SILVA, PROF, CEI'),
('49401','ISABELA CRISTHINA REIS DOS SANTOS',NULL,NULL,'PRETO_CAFE_T','49401','OFICIAL','GERALDA DE SOUZA ESPIN, EMEF'),
('43355_T','JOSE EDSON DA SILVA DINIZ','josediniz@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','43355','OFICIAL','JOSE DELIBO, VER., EMEF'),
('48631','JULIANA DUARTE MANHAS FERREIRA DO VALES','julianavales@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','48631','OFICIAL','ALCINA DOS SANTOS HECK, EMEF'),
('38993','MARIA CRISTINA FACHINI','mariafachini@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','38993','OFICIAL','MARIA LUCIA MEIRELLES JUNQUEIRA, CEI'),
('49399_T','PATRICK CESAR AMARAL FERREIRA',NULL,NULL,'PRETO_CAFE_T','49399','OFICIAL','DOMINGOS ADILSON CANESIN, EMEF'),
('31513_T','ROBERTO RODRIGUES PEREIRA JUNIOR','robertojunior@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','31513','OFICIAL','ALFEU LUIZ GASPARINI, PROFº., EMEF'),
('42447_T','ROGERIO APARECIDO NOVAES BARBOSA','rogeriobarbosa@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','42447','OFICIAL','JOSE DELIBO, VER., EMEF'),
('34384','ANDREA CALORA VENTURINO','andreaventurino@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','34384','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('49623','BRUNA DA SILVA DE SOUZA','brunadomingos@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','49623','OFICIAL','ROBERTO AFONSO PONTES, EMEI'),
('34556_M','CRISTIANE FALEIROS MARTINS','cristianemartins@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','34556','OFICIAL','IRIA JUNQUEIRA, DONA, EMEI'),
('43661','GABRIEL BULIANI DA SILVA SIQUEIRA','gabrielsiqueira@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','43661','OFICIAL','NELSON MACHADO, EMEF'),
('38232','KARINA MARDEGAN SARTOR','karinasartor@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','38232','OFICIAL','HILDA MOSCA, EMEI'),
('39311','MARIA DO CARMO TRABBOLD GUIMARAES','mariaguimaraes@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','39311','OFICIAL','MARIA REGINA CAVALCANTI, PROFA, CEI'),
('48837','STEPHANNY DA SILVA ORNEVO','stephannyornevo@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_M','48837','OFICIAL','ANTONIO PALOCCI, EMEF'),
('50417','VANESSA FUENTES COELHO',NULL,NULL,'QUEM_BRINCA_M','50417','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('35207_T','ALESSANDRA MARQUES TONELLI',NULL,NULL,'QUEM_BRINCA_T','35207','OFICIAL','SECRETARIA MUNICIPAL DA EDUCAÇÃO'),
('50309','DALILEIA FERREIRA DOS SANTOS',NULL,NULL,'QUEM_BRINCA_T','50309','OFICIAL','WILSON ROSELINO, EMEI'),
('49170','DAUANY TUPYNAMBA MORAES',NULL,NULL,'QUEM_BRINCA_T','49170','OFICIAL','AMELIA JUNQUEIRA, EMEI'),
('50122','DEBORA APARECIDA CORREA',NULL,NULL,'QUEM_BRINCA_T','50122','OFICIAL','HORTENCIO PEREIRA DA SILVA, PROF, CEI'),
('38847','EDNA MAIA DA SILVEIRA','ednasilveira@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_T','38847','OFICIAL','CECILIO FRAGUAS, CEI'),
('50355','GISELE CRISTINA PAULINO',NULL,NULL,'QUEM_BRINCA_T','50355','OFICIAL','CLORESDITH FERLIN FERREIRA, CEI'),
('38522','TAUANA BACHA DE SOUZA','tauanasouza@educacao.pmrp.sp.gov.br',NULL,'QUEM_BRINCA_T','38522','OFICIAL','ROBERTO AFONSO PONTES, EMEI')
on conflict (token) do nothing;

-- 7) MARA (41747): mantém as DUAS palestras (formulário de 06/07) ---
update presenca.participantes set token = '41747_T' where token = '41747';
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('41747_M','MARA ANGELICA DA SILVA','mangelicasilva@educacao.pmrp.sp.gov.br',NULL,'EDUC_ALIMENTAR_M','41747','OFICIAL','LEONOR MERTÍLIA COSTA, CEI')
on conflict (token) do nothing;

-- 8) LUCIANO SANTOS TONIOLO (45168): inscrição de última hora -------
--    Além das Telas — Manhã (21/07 08:00)
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('45168','LUCIANO SANTOS TONIOLO','lucianotoniolo@educacao.pmrp.sp.gov.br',NULL,'ALEM_TELAS_M','45168','OFICIAL','GERALDA DE SOUZA ESPIN, EMEF')
on conflict (token) do update set nome=excluded.nome, email=excluded.email, palestra_id=excluded.palestra_id, unidade=excluded.unidade;

-- 9) INSCRIÇÕES AVULSAS (convidados do Christian) ------------------
--    André (49633): rede municipal, recebe o comprovante por e-mail.
--    Elisa e Tássia: EXTERNAS (sem código e sem e-mail -> não entram
--    no envio de QR; constam nas listas e podem ser validadas pelo token SME).
insert into presenca.participantes (token,nome,email,cpf,palestra_id,codigo_funcional,origem,unidade) values
('49633','Andre de Jesus Minchio','andrem@educacao.pmrp.sp.gov.br',NULL,'PRETO_CAFE_T','49633','OFICIAL','FAUSTINO JARRUCHE, EMEF'),
('SME123','Elisa Lunardi',NULL,NULL,'EDUCAR_CONVIVER_M',NULL,'CONVIDADA','Convidada externa'),
('SME124','Tassia Veiga Faccioli',NULL,NULL,'QUEM_BRINCA_M',NULL,'CONVIDADA','Escola parceira')
on conflict (token) do update set nome=excluded.nome, palestra_id=excluded.palestra_id, origem=excluded.origem, unidade=excluded.unidade;

commit;

-- CONFERÊNCIA ------------------------------------------------------
select count(*) as total_participantes from presenca.participantes;
select palestra_id, count(*) from presenca.participantes
where palestra_id like 'DIALOGOS%' group by palestra_id order by 1;  -- esperado: 47 M / 50 T
select token, nome, palestra_id from presenca.participantes
where codigo_funcional in ('41747','45168','50402','50460','40030','38268','49633')
   or token in ('SME123','SME124')
order by nome, token;  -- Mara 2 linhas, Luciano, Gabrielas, Cristopher, Andre, Elisa, Tassia
